### ISSUE TITLE
Can't change the default  language  

### ISSUE THREAD

**Issue by mohanagy** [AlternativaPlatform/react-redux-localization#1]
Hi there, 
I faced a problem with changing the default language 
I don't use `en` as default language  or even as language 
I'm using `Arabic` and `Hebrew`
so the default language should be one of them 'ar' or 'he'
so is there a way?

**Comment by pa3** [comment]
Hi. Initial language is determined by the state of your `redux` store. So either start your app with an initial state, containing desired language as current locale and/or use your own locale reducer, which will fallback to the language of your choice when no initial one is provided.
 
Feel free to comment if you think issue is not solved.
